#!/bin/bash
for lmutil in /shared/ucl/apps/lm-utils/bin/lmutil /shared/ucl/apps/Matlab/R2019b/full/etc/glnxa64/lmutil /shared/ucl/apps/flexlm/Intel/flexlm/lmutil
do
[ -x ${lmutil} ] && exec /usr/bin/sudo -u ccsplma ${lmutil} "$@"
done
echo "No lmutil found"
